language: c
compiler:
  - clang
  - gcc-4.4
  - gcc-4.6
  - gcc-4.7
  - gcc-4.8
  - gcc
  - tcc
install:
  - sudo apt-get update
  - sudo apt-get install gcc-4.4 gcc-4.7 gcc-4.8 gcc-4.6 tcc
script:
  - cd build
  - cmake ..
#  - autoreconf -fi
#  - ./configure --enable-debug
  - make
    #after_success:
